services:
  app:
    container_name: message
    build: ./
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    container_name: database
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: Message
      POSTGRES_USER: david
      POSTGRES_PASSWORD: 1234567890